using System.Text;
using PZAdvancedServerManager.Core.Domain;
using PZAdvancedServerManager.Core.Pz;

namespace PZAdvancedServerManager.Core.Packaging;

public static class ControlModGenerator
{
    public static void GenerateStandalone(string modsRoot, PackageProject project)
    {
        var root = Path.Combine(modsRoot, project.ControlModId);
        NoticeModGenerator.WriteManifest(root, project.ControlModId, $"{project.Name} — control", "In-game pack status and administrator console generated by PZ Advanced Server Manager.");
        WriteFiles(root, project);
    }

    public static void InjectIntoFusion(string fusionRoot, PackageProject project) => WriteFiles(fusionRoot, project);

    private static void WriteFiles(string root, PackageProject project)
    {
        var clientPath = Path.Combine(root, "common", "media", "lua", "client", "PZASM_ControlClient.lua");
        var serverPath = Path.Combine(root, "common", "media", "lua", "server", "PZASM_ControlServer.lua");
        Directory.CreateDirectory(Path.GetDirectoryName(clientPath)!);
        Directory.CreateDirectory(Path.GetDirectoryName(serverPath)!);
        File.WriteAllText(clientPath, CreateClient(project), new UTF8Encoding(false));
        File.WriteAllText(serverPath, CreateServer(project), new UTF8Encoding(false));
    }

    private static string CreateClient(PackageProject project)
    {
        var mods = string.Join(",\n", project.Mods.Where(x => x.Enabled).OrderBy(x => x.Order).ThenBy(x => x.Name).Select(x =>
            $"    {{ id = {LuaString(x.ModId)}, name = {LuaString(x.Name)}, version = {LuaString(x.DisplayVersion)}, workshop = {LuaString(x.WorkshopId.ToString())}, localSource = {(x.WorkshopId == 0 ? "true" : "false")}, author = {LuaString(x.Author)}, profile = {LuaString(string.IsNullOrWhiteSpace(x.SelectedVersionFolder) ? "root / legacy" : x.SelectedVersionFolder)}, buildCompatible = {(IsBuildCompatible(project, x) ? "true" : "false")}, requires = {{ {string.Join(", ", x.RequiredModIds.Select(LuaString))} }} }}"));
        return $$"""
require "ISUI/ISPanel"
require "ISUI/ISScrollingListBox"
require "ISUI/ISButton"
require "ISUI/ISLabel"

local PZASM_PACK_NAME = {{LuaString(project.Name)}}
local PZASM_WORKSHOP_ID = {{LuaString(project.PublishedWorkshopId == 0 ? "pending" : project.PublishedWorkshopId.ToString())}}
local PZASM_POSITION_KEY = {{LuaString(project.ControlModId + "_HudPosition")}}
local PZASM_MODS = {
{{mods}}
}
local PZASM_TEXT = {
    fr = { ready="Prêt", refresh="Actualiser", server="État serveur", broadcast="Diffuser l'état du pack", close="Fermer", active="ACTIF", missing="ABSENT", mods="mods actifs", localScan="analyse locale terminée", requesting="Interrogation du serveur...", sending="Diffusion administrateur...", denied="Autorisation administrateur requise", admin="OUTILS ADMIN", restart="Toute modification des mods nécessite un redémarrage coordonné. Aucun rechargement à chaud n'est effectué.", workshop="Workshop ID", author="Auteur", version="Version du pack", modId="Mod ID", source="Source", localSource="Fichier local", unknown="Non renseigné", hudHint="Cliquer pour ouvrir - glisser pour déplacer", serverOnline="Serveur en ligne", players="joueur(s)", expectedMods="mods attendus" },
    en = { ready="Ready", refresh="Refresh", server="Server status", broadcast="Broadcast pack status", close="Close", active="ACTIVE", missing="MISSING", mods="mods active", localScan="local scan complete", requesting="Requesting server status...", sending="Sending administrator broadcast...", denied="Administrator permission required", admin="ADMIN TOOLS", restart="Mod changes require a coordinated restart. No files are hot-reloaded.", workshop="Workshop ID", author="Author", version="Pack version", modId="Mod ID", source="Source", localSource="Local files", unknown="Not provided", hudHint="Click to open - drag to move", serverOnline="Server online", players="player(s)", expectedMods="expected mods" },
    es = { ready="Listo", refresh="Actualizar", server="Estado servidor", broadcast="Difundir estado del pack", close="Cerrar", active="ACTIVO", missing="AUSENTE", mods="mods activos", localScan="análisis local terminado", requesting="Consultando servidor...", sending="Enviando difusión...", denied="Se requiere permiso de administrador", admin="HERRAMIENTAS ADMIN", restart="Los cambios de mods requieren un reinicio coordinado. No se recargan archivos en caliente.", workshop="Workshop ID", author="Autor", version="Versión del pack", modId="Mod ID", source="Origen", localSource="Archivos locales", unknown="No indicado", hudHint="Clic para abrir - arrastrar para mover", serverOnline="Servidor en línea", players="jugador(es)", expectedMods="mods esperados" },
    de = { ready="Bereit", refresh="Aktualisieren", server="Serverstatus", broadcast="Packstatus senden", close="Schließen", active="AKTIV", missing="FEHLT", mods="Mods aktiv", localScan="lokale Prüfung abgeschlossen", requesting="Serverstatus wird abgefragt...", sending="Admin-Mitteilung wird gesendet...", denied="Administratorrechte erforderlich", admin="ADMIN-WERKZEUGE", restart="Mod-Änderungen erfordern einen koordinierten Neustart. Dateien werden nicht im laufenden Betrieb neu geladen.", workshop="Workshop ID", author="Autor", version="Pack-Version", modId="Mod ID", source="Quelle", localSource="Lokale Dateien", unknown="Nicht angegeben", hudHint="Klicken zum Öffnen - ziehen zum Verschieben", serverOnline="Server online", players="Spieler", expectedMods="erwartete Mods" },
    pt = { ready="Pronto", refresh="Atualizar", server="Estado servidor", broadcast="Divulgar estado do pack", close="Fechar", active="ATIVO", missing="AUSENTE", mods="mods ativos", localScan="verificação local concluída", requesting="Consultando servidor...", sending="Enviando anúncio...", denied="Permissão de administrador necessária", admin="FERRAMENTAS ADMIN", restart="Alterações de mods exigem reinício coordenado. Nenhum arquivo é recarregado a quente.", workshop="Workshop ID", author="Autor", version="Versão do pack", modId="Mod ID", source="Origem", localSource="Arquivos locais", unknown="Não informado", hudHint="Clique para abrir - arraste para mover", serverOnline="Servidor online", players="jogador(es)", expectedMods="mods esperados" },
    zh = { ready="就绪", refresh="刷新", server="服务器状态", broadcast="广播整合包状态", close="关闭", active="已启用", missing="缺失", mods="个模组已启用", localScan="本地检查完成", requesting="正在查询服务器...", sending="正在发送管理员广播...", denied="需要管理员权限", admin="管理员工具", restart="模组变更需要协调重启，不会热重载文件。", workshop="Workshop ID", author="作者", version="整合包版本", modId="Mod ID", source="来源", localSource="本地文件", unknown="未提供", hudHint="点击打开 - 拖动移动", serverOnline="服务器在线", players="玩家", expectedMods="预期模组" }
}
local PZASM_DIAGNOSTICS = {
    fr = { inactive="INACTIF", reason="Diagnostic", legacy="Aucune version Build 42 compatible. Le dossier racine/legacy est ignoré par PZ 42.", undiscovered="Mod ID non découvert par Project Zomboid. Vérifiez mod.info et le dossier versionné.", dependency="Dépendance inactive", serverInactive="Absent de la liste active du serveur. Vérifiez Mods= et le journal serveur.", clientInactive="Présent sur le serveur mais inactif sur ce client. Vérifiez le téléchargement et le journal client.", installedInactive="Installé et compatible, mais non activé dans cette session.", serverUnknown="Non actif localement. Interrogez le serveur pour distinguer serveur et client.", profile="Profil PZ" },
    en = { inactive="INACTIVE", reason="Diagnosis", legacy="No compatible Build 42 version. PZ 42 ignores the root/legacy mod files.", undiscovered="Mod ID was not discovered by Project Zomboid. Check mod.info and the versioned folder.", dependency="Inactive dependency", serverInactive="Missing from the server active list. Check Mods= and the server log.", clientInactive="Active on the server but inactive on this client. Check the download and client log.", installedInactive="Installed and compatible, but not enabled in this session.", serverUnknown="Not active locally. Query the server to distinguish server and client state.", profile="PZ profile" },
    es = { inactive="INACTIVO", reason="Diagnóstico", legacy="No hay una versión compatible con Build 42. PZ 42 ignora los archivos raíz/legacy.", undiscovered="Project Zomboid no descubrió el Mod ID. Comprueba mod.info y la carpeta versionada.", dependency="Dependencia inactiva", serverInactive="Ausente de la lista activa del servidor. Comprueba Mods= y el registro.", clientInactive="Activo en el servidor pero inactivo en este cliente. Comprueba la descarga y el registro.", installedInactive="Instalado y compatible, pero no activado en esta sesión.", serverUnknown="No está activo localmente. Consulta el servidor para localizar la causa.", profile="Perfil PZ" },
    de = { inactive="INAKTIV", reason="Diagnose", legacy="Keine kompatible Build-42-Version. PZ 42 ignoriert Root-/Legacy-Dateien.", undiscovered="Die Mod-ID wurde von Project Zomboid nicht erkannt. mod.info und Versionsordner prüfen.", dependency="Inaktive Abhängigkeit", serverInactive="Nicht in der aktiven Serverliste. Mods= und Serverprotokoll prüfen.", clientInactive="Auf dem Server aktiv, auf diesem Client inaktiv. Download und Clientprotokoll prüfen.", installedInactive="Installiert und kompatibel, aber in dieser Sitzung nicht aktiviert.", serverUnknown="Lokal nicht aktiv. Serverstatus abfragen, um die Ursache einzugrenzen.", profile="PZ-Profil" },
    pt = { inactive="INATIVO", reason="Diagnóstico", legacy="Nenhuma versão compatível com Build 42. O PZ 42 ignora arquivos raiz/legacy.", undiscovered="O Mod ID não foi descoberto pelo Project Zomboid. Verifique mod.info e a pasta versionada.", dependency="Dependência inativa", serverInactive="Ausente da lista ativa do servidor. Verifique Mods= e o log.", clientInactive="Ativo no servidor, mas inativo neste cliente. Verifique o download e o log.", installedInactive="Instalado e compatível, mas não ativado nesta sessão.", serverUnknown="Não está ativo localmente. Consulte o servidor para localizar a causa.", profile="Perfil PZ" },
    zh = { inactive="未启用", reason="诊断", legacy="没有兼容 Build 42 的版本。PZ 42 会忽略根目录/旧版文件。", undiscovered="Project Zomboid 未发现此 Mod ID。请检查 mod.info 和版本目录。", dependency="未启用的依赖", serverInactive="不在服务器启用列表中。请检查 Mods= 和服务器日志。", clientInactive="服务器已启用，但此客户端未启用。请检查下载和客户端日志。", installedInactive="已安装且兼容，但本次会话未启用。", serverUnknown="本地未启用。请查询服务器状态以定位原因。", profile="PZ 配置" }
}
local PZASM_WINDOW = nil
local PZASM_HUD_BUTTON = nil
local PZASM_SERVER_ACTIVE = nil

local function pzasmLanguage()
    local value = "en"
    local ok, detected = pcall(function()
        if Translator and Translator.getLanguage then return tostring(Translator.getLanguage():name()) end
        if getCore and getCore().getOptionLanguageName then return tostring(getCore():getOptionLanguageName()) end
        return "en"
    end)
    if ok and detected then value = string.lower(detected) end
    if string.find(value, "fr") or string.find(value, "french") then return "fr" end
    if string.find(value, "es") or string.find(value, "spanish") then return "es" end
    if string.find(value, "de") or string.find(value, "german") then return "de" end
    if string.find(value, "pt") or string.find(value, "portugu") then return "pt" end
    if string.find(value, "zh") or string.find(value, "cn") or string.find(value, "chinese") then return "zh" end
    return "en"
end

local function pzasmText() return PZASM_TEXT[pzasmLanguage()] or PZASM_TEXT.en end
local function pzasmDiagnosticText() return PZASM_DIAGNOSTICS[pzasmLanguage()] or PZASM_DIAGNOSTICS.en end

local function pzasmIsAdmin()
    local ok, value = pcall(function() return string.lower(tostring(getAccessLevel() or "")) end)
    return ok and (value == "admin" or value == "moderator" or value == "overseer" or value == "gm")
end

local function pzasmDrawField(ui, label, value, x, y)
    local labelText = tostring(label) .. ":"
    ui:drawText(labelText, x, y, 0.55, 0.67, 0.57, 1, UIFont.Small)
    local offset = getTextManager():MeasureStringX(UIFont.Small, labelText) + 8
    ui:drawText(tostring(value), x + offset, y, 0.91, 0.94, 0.90, 1, UIFont.Small)
end

local function pzasmReadHudPosition()
    local defaultX = 18
    local defaultY = getCore():getScreenHeight() - 54
    local ok, savedX, savedY = pcall(function()
        local player = getPlayer()
        local data = player and player:getModData()
        local saved = data and data[PZASM_POSITION_KEY]
        return saved and tonumber(saved.x), saved and tonumber(saved.y)
    end)
    if ok and savedX and savedY then return savedX, savedY end
    return defaultX, defaultY
end

local function pzasmSaveHudPosition(button)
    pcall(function()
        local player = getPlayer()
        if not player then return end
        local data = player:getModData()
        data[PZASM_POSITION_KEY] = { x = math.floor(button.x), y = math.floor(button.y) }
    end)
end

PZASMControlWindow = ISPanel:derive("PZASMControlWindow")

local function pzasmInspectMod(mod, active)
    local diagnostic = pzasmDiagnosticText()
    local enabled = active and active:contains(mod.id) or false
    if enabled then return true, true, "" end

    local installed = false
    pcall(function()
        local info = getModInfoByID and getModInfoByID(mod.id) or nil
        installed = info ~= nil
    end)
    local missingDependencies = {}
    for _, dependencyId in ipairs(mod.requires or {}) do
        if not active or not active:contains(dependencyId) then table.insert(missingDependencies, dependencyId) end
    end

    if not mod.buildCompatible then return false, installed, diagnostic.legacy end
    if not installed then return false, false, diagnostic.undiscovered end
    if #missingDependencies > 0 then return false, true, diagnostic.dependency .. ": " .. table.concat(missingDependencies, ", ") end
    if PZASM_SERVER_ACTIVE ~= nil then
        if PZASM_SERVER_ACTIVE[mod.id] then return false, true, diagnostic.clientInactive end
        return false, true, diagnostic.serverInactive
    end
    return false, true, diagnostic.installedInactive .. " " .. diagnostic.serverUnknown
end

function PZASMControlWindow.drawModItem(list, y, item, alt)
    local height = item.height or 136
    if (y + list:getYScroll() + height < 0) or (y + list:getYScroll() >= list.height) then
        return y + height
    end

    local entry = item.item
    local mod = entry.mod
    local text = pzasmText()
    local enabled = entry.enabled
    local installed = entry.installed
    local statusText = enabled and text.active or installed and pzasmDiagnosticText().inactive or text.missing
    local statusColor = enabled and { r=0.55, g=0.82, b=0.31 } or installed and { r=0.95, g=0.66, b=0.18 } or { r=0.91, g=0.34, b=0.28 }
    local cardX = 4
    local cardY = y + 4
    local cardWidth = list:getWidth() - 18
    local cardHeight = height - 8

    list:drawRect(cardX, cardY, cardWidth, cardHeight, 0.82, 0.055, 0.075, 0.060)
    if list.mouseoverselected == item.index and list:isMouseOver() and not list:isMouseOverScrollBar() then
        list:drawRect(cardX, cardY, cardWidth, cardHeight, 0.10, 0.58, 0.76, 0.42)
    end
    list:drawRect(cardX, cardY, 4, cardHeight, 1, statusColor.r, statusColor.g, statusColor.b)
    list:drawRectBorder(cardX, cardY, cardWidth, cardHeight, 0.72, 0.25, 0.35, 0.27)

    list:drawText("#" .. tostring(entry.order), cardX + 17, cardY + 14, 0.48, 0.64, 0.43, 1, UIFont.Small)
    list:drawText(tostring(mod.name), cardX + 52, cardY + 11, 0.95, 0.97, 0.94, 1, UIFont.Medium)
    local statusWidth = getTextManager():MeasureStringX(UIFont.Small, statusText) + 18
    local statusX = cardX + cardWidth - statusWidth - 12
    list:drawRect(statusX, cardY + 10, statusWidth, 22, 0.96, 0.035, 0.052, 0.040)
    list:drawRect(statusX, cardY + 10, statusWidth, 22, 0.22, statusColor.r, statusColor.g, statusColor.b)
    list:drawRectBorder(statusX, cardY + 10, statusWidth, 22, 0.70, statusColor.r, statusColor.g, statusColor.b)
    list:drawText(statusText, statusX + 9, cardY + 13, statusColor.r, statusColor.g, statusColor.b, 1, UIFont.Small)
    local author = tostring(mod.author or "")
    if author == "" then author = text.unknown end
    pzasmDrawField(list, text.author, author, cardX + 18, cardY + 39)
    pzasmDrawField(list, text.version, tostring(mod.version or text.unknown), cardX + 18, cardY + 59)
    pzasmDrawField(list, text.modId, tostring(mod.id), cardX + 18, cardY + 79)
    local source = mod.localSource and text.localSource or (text.workshop .. " " .. tostring(mod.workshop))
    pzasmDrawField(list, text.source, source, math.floor(cardX + cardWidth * 0.52), cardY + 79)
    pzasmDrawField(list, pzasmDiagnosticText().profile, tostring(mod.profile or "?"), cardX + 18, cardY + 99)
    if not enabled then
        pzasmDrawField(list, pzasmDiagnosticText().reason, tostring(entry.reason or pzasmDiagnosticText().serverUnknown), cardX + 18, cardY + 119)
    end
    return y + height
end

function PZASMControlWindow:new(x, y, width, height)
    local panel = ISPanel.new(self, x, y, width, height)
    panel.backgroundColor = { r=0.035, g=0.052, b=0.040, a=0.98 }
    panel.borderColor = { r=0.48, g=0.72, b=0.25, a=1 }
    panel.moveWithMouse = true
    panel.serverStatus = "Ready"
    return panel
end

function PZASMControlWindow:initialise()
    ISPanel.initialise(self)
    local text = pzasmText()
    self.summary = ISLabel:new(22, 61, 20, "", 0.66, 0.76, 0.67, 1, UIFont.Small, true)
    self.summary:initialise()
    self:addChild(self.summary)

    self.modList = ISScrollingListBox:new(18, 86, self.width - 36, self.height - 200)
    self.modList:initialise()
    self.modList:instantiate()
    self.modList.backgroundColor = { r=0.025, g=0.038, b=0.029, a=0.72 }
    self.modList.borderColor = { r=0.23, g=0.34, b=0.24, a=0.85 }
    self.modList.drawBorder = true
    self.modList.itemheight = 136
    self.modList.doDrawItem = PZASMControlWindow.drawModItem
    self.modList.selected = -1
    self:addChild(self.modList)

    self.status = ISLabel:new(22, self.height - 59, 20, text.ready, 0.70, 0.82, 0.68, 1, UIFont.Small, true)
    self.status:initialise()
    self:addChild(self.status)

    self.refreshButton = ISButton:new(self.width - 366, self.height - 68, 105, 34, text.refresh, self, PZASMControlWindow.onRefresh)
    self.refreshButton:initialise()
    self:addChild(self.refreshButton)

    self.serverButton = ISButton:new(self.width - 253, self.height - 68, 105, 34, text.server, self, PZASMControlWindow.onServerStatus)
    self.serverButton:initialise()
    self:addChild(self.serverButton)

    self.adminButton = ISButton:new(self.width - 366, self.height - 106, 218, 30, text.broadcast, self, PZASMControlWindow.onBroadcast)
    self.adminButton:initialise()
    self.adminButton:setVisible(pzasmIsAdmin())
    self:addChild(self.adminButton)

    self.closeButton = ISButton:new(self.width - 140, self.height - 68, 118, 34, text.close, self, PZASMControlWindow.onClose)
    self.closeButton:initialise()
    self:addChild(self.closeButton)
    self:refresh()
end

function PZASMControlWindow:prerender()
    ISPanel.prerender(self)
    self:drawRect(0, 0, self.width, 46, 0.98, 0.08, 0.14, 0.09)
    self:drawRect(0, 45, self.width, 2, 1, 0.48, 0.72, 0.25)
    self:drawText("PZ", 19, 13, 0.66, 0.86, 0.38, 1, UIFont.Medium)
    self:drawText("ADVANCED SERVER MANAGER", 58, 14, 0.92, 0.95, 0.90, 1, UIFont.Small)
    local role = pzasmIsAdmin() and "ADMIN" or "PLAYER"
    self:drawTextRight(role, self.width - 20, 15, 0.66, 0.86, 0.38, 1, UIFont.Small)
end

function PZASMControlWindow:refresh()
    local text = pzasmText()
    local active = getActivatedMods()
    local activeCount = 0
    local previousScroll = self.modList:getYScroll()
    self.modList:clear()
    self.modList:setScrollHeight(0)
    for index, mod in ipairs(PZASM_MODS) do
        local enabled, installed, reason = pzasmInspectMod(mod, active)
        if enabled then activeCount = activeCount + 1 end
        local row = self.modList:addItem(mod.name, { mod = mod, enabled = enabled, installed = installed, reason = reason, order = index })
        row.height = enabled and 116 or 144
    end
    self.modList:setYScroll(previousScroll)
    self.summary:setName(text.workshop .. " " .. PZASM_WORKSHOP_ID .. "   |   " .. tostring(activeCount) .. "/" .. tostring(#PZASM_MODS) .. " " .. text.mods .. "   |   F8")
    self.status:setName(tostring(activeCount) .. "/" .. tostring(#PZASM_MODS) .. " - " .. text.localScan)
end

function PZASMControlWindow:onRefresh() self:refresh() end
function PZASMControlWindow:onServerStatus()
    self.status:setName(pzasmText().requesting)
    pcall(function() sendClientCommand(getPlayer(), "PZASM_Control", "status", {}) end)
end
function PZASMControlWindow:onBroadcast()
    if not pzasmIsAdmin() then return end
    self.status:setName(pzasmText().sending)
    pcall(function() sendClientCommand(getPlayer(), "PZASM_Control", "broadcast", { pack = PZASM_PACK_NAME, workshop = PZASM_WORKSHOP_ID, count = #PZASM_MODS }) end)
end
function PZASMControlWindow:onClose() self:setVisible(false) end

local function pzasmOpenControl()
    if not PZASM_WINDOW then
        local width = math.min(900, getCore():getScreenWidth() - 70)
        local height = math.min(680, getCore():getScreenHeight() - 80)
        PZASM_WINDOW = PZASMControlWindow:new((getCore():getScreenWidth() - width) / 2, (getCore():getScreenHeight() - height) / 2, width, height)
        PZASM_WINDOW:initialise()
        PZASM_WINDOW:addToUIManager()
    else
        PZASM_WINDOW:setVisible(true)
        PZASM_WINDOW:bringToTop()
        PZASM_WINDOW:refresh()
    end
end

_G.PZASM_OpenControl = pzasmOpenControl

local PZASMHudButton = ISButton:derive("PZASMHudButton")

function PZASMHudButton:new(x, y, width, height, title, onclick)
    local button = ISButton.new(self, x, y, width, height, title, nil, onclick)
    button.dragging = false
    button.dragged = false
    button.dragDistance = 0
    return button
end

function PZASMHudButton:onMouseDown(x, y)
    ISButton.onMouseDown(self, x, y)
    self.dragging = true
    self.dragged = false
    self.dragDistance = 0
    self:setCapture(true)
    self:bringToTop()
end

function PZASMHudButton:moveBy(dx, dy)
    if not self.dragging then return end
    self.dragDistance = self.dragDistance + math.abs(dx) + math.abs(dy)
    if self.dragDistance > 4 then self.dragged = true end
    if self.dragged then
        self:setX(self.x + dx)
        self:setY(self.y + dy)
        self:bringToTop()
    end
end

function PZASMHudButton:onMouseMove(dx, dy)
    ISButton.onMouseMove(self, dx, dy)
    self:moveBy(dx, dy)
end

function PZASMHudButton:onMouseMoveOutside(dx, dy)
    ISButton.onMouseMoveOutside(self, dx, dy)
    self:moveBy(dx, dy)
end

function PZASMHudButton:onMouseUp(x, y)
    local wasDragged = self.dragged
    self.dragging = false
    self:setCapture(false)
    if wasDragged then
        self.pressed = false
        pzasmSaveHudPosition(self)
        return
    end
    ISButton.onMouseUp(self, x, y)
end

function PZASMHudButton:onMouseUpOutside(x, y)
    local wasDragged = self.dragged
    self.dragging = false
    self:setCapture(false)
    ISButton.onMouseUpOutside(self, x, y)
    if wasDragged then pzasmSaveHudPosition(self) end
end

local function pzasmCreateHudButton()
    if PZASM_HUD_BUTTON then return end
    local x, y = pzasmReadHudPosition()
    PZASM_HUD_BUTTON = PZASMHudButton:new(x, y, 54, 34, "PZ", pzasmOpenControl)
    PZASM_HUD_BUTTON:initialise()
    PZASM_HUD_BUTTON.backgroundColor = { r=0.035, g=0.052, b=0.040, a=0.94 }
    PZASM_HUD_BUTTON.backgroundColorMouseOver = { r=0.20, g=0.34, b=0.16, a=0.98 }
    PZASM_HUD_BUTTON.borderColor = { r=0.48, g=0.72, b=0.25, a=1 }
    PZASM_HUD_BUTTON:setTooltip(pzasmText().hudHint)
    PZASM_HUD_BUTTON:setAnchorLeft(true)
    PZASM_HUD_BUTTON:setAnchorRight(false)
    PZASM_HUD_BUTTON:setAnchorTop(false)
    PZASM_HUD_BUTTON:setAnchorBottom(true)
    PZASM_HUD_BUTTON:addToUIManager()
end

local function pzasmKeyPressed(key)
    if Keyboard and key == Keyboard.KEY_F8 then pzasmOpenControl() end
end

local function pzasmServerCommand(module, command, args)
    if module ~= "PZASM_Control" then return end
    if command == "status" and PZASM_WINDOW then
        local text = pzasmText()
        PZASM_SERVER_ACTIVE = {}
        for modId in string.gmatch(tostring(args.activeMods or ""), "[^;]+") do PZASM_SERVER_ACTIVE[modId] = true end
        PZASM_WINDOW:refresh()
        PZASM_WINDOW.status:setName(text.serverOnline .. " - " .. tostring(args.players or 0) .. " " .. text.players .. " - " .. tostring(args.expected or #PZASM_MODS) .. " " .. text.expectedMods)
    elseif command == "announcement" then
        if HaloTextHelper and getPlayer() then HaloTextHelper.addText(getPlayer(), tostring(args.message or "Pack status updated"), HaloTextHelper.getColorGreen()) end
    elseif command == "denied" and PZASM_WINDOW then
        PZASM_WINDOW.status:setName(pzasmText().denied)
    end
end

Events.OnGameStart.Add(pzasmCreateHudButton)
Events.OnKeyPressed.Add(pzasmKeyPressed)
Events.OnServerCommand.Add(pzasmServerCommand)
""";
    }

    private static string CreateServer(PackageProject project) => $$"""
local PZASM_EXPECTED_MODS = {{project.Mods.Count(x => x.Enabled)}}
local PZASM_EXPECTED_IDS = { {{string.Join(", ", project.Mods.Where(x => x.Enabled).OrderBy(x => x.Order).Select(x => LuaString(x.ModId)))}} }

local function pzasmIsAdmin(player)
    if not player then return false end
    local value = string.lower(tostring(player:getAccessLevel() or ""))
    return value == "admin" or value == "moderator" or value == "overseer" or value == "gm"
end

local function pzasmPlayerCount()
    local ok, players = pcall(function() return getOnlinePlayers() end)
    return ok and players and players:size() or 0
end

local function pzasmActiveModIds()
    local active = getActivatedMods and getActivatedMods() or nil
    local result = {}
    if active then
        for _, modId in ipairs(PZASM_EXPECTED_IDS) do
            if active:contains(modId) then table.insert(result, modId) end
        end
    end
    return table.concat(result, ";")
end

local function pzasmClientCommand(module, command, player, args)
    if module ~= "PZASM_Control" then return end
    if command == "status" then
        sendServerCommand(player, "PZASM_Control", "status", { players = pzasmPlayerCount(), expected = PZASM_EXPECTED_MODS, activeMods = pzasmActiveModIds() })
        return
    end
    if command == "broadcast" then
        if not pzasmIsAdmin(player) then
            sendServerCommand(player, "PZASM_Control", "denied", {})
            return
        end
        local pack = tostring(args and args.pack or "server pack")
        local message = "[PZASM] " .. pack .. ": " .. tostring(PZASM_EXPECTED_MODS) .. " managed mods active. Changes require a coordinated restart."
        sendServerCommand("PZASM_Control", "announcement", { message = message })
    end
end

Events.OnClientCommand.Add(pzasmClientCommand)
""";

    private static string LuaString(string value) => "\"" + value
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal)
        .Replace("\r", string.Empty, StringComparison.Ordinal)
        .Replace("\n", "\\n", StringComparison.Ordinal) + "\"";

    private static bool IsBuildCompatible(PackageProject project, PackageModReference mod)
    {
        if (!int.TryParse(project.TargetPzVersion.Split('.', '-', '_').FirstOrDefault(), out var targetMajor) || targetMajor < 42) return true;
        if (int.TryParse(mod.SelectedVersionFolder.Split('.', '-', '_').FirstOrDefault(), out var folderMajor) && folderMajor >= 42) return true;
        if (!Directory.Exists(mod.BuildSourceRoot)) return false;
        var manifest = PzVersionSelector.SelectManifest(mod.BuildSourceRoot, project.TargetPzVersion, out var selected);
        if (string.IsNullOrWhiteSpace(manifest)) return false;
        if (int.TryParse(selected.Split('.', '-', '_').FirstOrDefault(), out folderMajor) && folderMajor >= 42) return true;
        var info = ModInfoParser.Parse(manifest);
        foreach (var key in new[] { "pzversion", "versionMin", "versionMax" })
        {
            if (!info.Properties.TryGetValue(key, out var value)) continue;
            if (int.TryParse(value.Trim().TrimStart('v', 'V').Split('.', '-', '_', ' ').FirstOrDefault(), out var major) && major >= 42) return true;
        }
        return false;
    }
}
