using System.Text;
using PZAdvancedServerManager.Core.Domain;

namespace PZAdvancedServerManager.Core.Packaging;

public static class ControlModGenerator
{
    public static void GenerateStandalone(string modsRoot, PackageProject project)
    {
        var root = Path.Combine(modsRoot, project.ControlModId);
        NoticeModGenerator.WriteManifest(root, project.ControlModId, $"{project.Name} — control", "In-game pack status and administrator console generated by PZ Advanced Server Manager.");
        WriteFiles(root, project);
    }

    public static void InjectIntoFusion(string fusionRoot, PackageProject project) => WriteFiles(fusionRoot, project);

    private static void WriteFiles(string root, PackageProject project)
    {
        var clientPath = Path.Combine(root, "common", "media", "lua", "client", "PZASM_ControlClient.lua");
        var serverPath = Path.Combine(root, "common", "media", "lua", "server", "PZASM_ControlServer.lua");
        Directory.CreateDirectory(Path.GetDirectoryName(clientPath)!);
        Directory.CreateDirectory(Path.GetDirectoryName(serverPath)!);
        File.WriteAllText(clientPath, CreateClient(project), new UTF8Encoding(false));
        File.WriteAllText(serverPath, CreateServer(project), new UTF8Encoding(false));
    }

    private static string CreateClient(PackageProject project)
    {
        var mods = string.Join(",\n", project.Mods.Where(x => x.Enabled).OrderBy(x => x.Order).ThenBy(x => x.Name).Select(x =>
            $"    {{ id = {LuaString(x.ModId)}, name = {LuaString(x.Name)}, version = {LuaString(x.DisplayVersion)}, workshop = {LuaString(x.WorkshopId == 0 ? "local" : x.WorkshopId.ToString())}, author = {LuaString(string.IsNullOrWhiteSpace(x.Author) ? "—" : x.Author)} }}"));
        return $$"""
require "ISUI/ISPanel"
require "ISUI/ISRichTextPanel"
require "ISUI/ISButton"
require "ISUI/ISLabel"

local PZASM_PACK_NAME = {{LuaString(project.Name)}}
local PZASM_WORKSHOP_ID = {{LuaString(project.PublishedWorkshopId == 0 ? "pending" : project.PublishedWorkshopId.ToString())}}
local PZASM_MODS = {
{{mods}}
}
local PZASM_TEXT = {
    fr = { ready="Prêt", refresh="Actualiser", server="État serveur", broadcast="Diffuser l'état du pack", close="Fermer", active="ACTIF", missing="ABSENT", expected="Attendue", loaded="Chargée", mods="mods inclus actifs", localScan="analyse locale terminée", requesting="Interrogation du serveur…", sending="Diffusion administrateur…", denied="Autorisation administrateur requise", admin="OUTILS ADMIN", restart="Toute modification des mods nécessite un redémarrage coordonné. Aucun rechargement à chaud n'est effectué." },
    en = { ready="Ready", refresh="Refresh", server="Server status", broadcast="Broadcast pack status", close="Close", active="ACTIVE", missing="MISSING", expected="Expected", loaded="Loaded", mods="included mods active", localScan="local scan complete", requesting="Requesting server status…", sending="Sending administrator broadcast…", denied="Administrator permission required", admin="ADMIN TOOLS", restart="Mod changes require a coordinated restart. No files are hot-reloaded." },
    es = { ready="Listo", refresh="Actualizar", server="Estado servidor", broadcast="Difundir estado del pack", close="Cerrar", active="ACTIVO", missing="AUSENTE", expected="Esperada", loaded="Cargada", mods="mods incluidos activos", localScan="análisis local terminado", requesting="Consultando servidor…", sending="Enviando difusión…", denied="Se requiere permiso de administrador", admin="HERRAMIENTAS ADMIN", restart="Los cambios de mods requieren un reinicio coordinado. No se recargan archivos en caliente." },
    de = { ready="Bereit", refresh="Aktualisieren", server="Serverstatus", broadcast="Packstatus senden", close="Schließen", active="AKTIV", missing="FEHLT", expected="Erwartet", loaded="Geladen", mods="enthaltene Mods aktiv", localScan="lokale Prüfung abgeschlossen", requesting="Serverstatus wird abgefragt…", sending="Admin-Mitteilung wird gesendet…", denied="Administratorrechte erforderlich", admin="ADMIN-WERKZEUGE", restart="Mod-Änderungen erfordern einen koordinierten Neustart. Dateien werden nicht im laufenden Betrieb neu geladen." },
    pt = { ready="Pronto", refresh="Atualizar", server="Estado servidor", broadcast="Divulgar estado do pack", close="Fechar", active="ATIVO", missing="AUSENTE", expected="Esperada", loaded="Carregada", mods="mods incluídos ativos", localScan="verificação local concluída", requesting="Consultando servidor…", sending="Enviando anúncio…", denied="Permissão de administrador necessária", admin="FERRAMENTAS ADMIN", restart="Alterações de mods exigem reinício coordenado. Nenhum arquivo é recarregado a quente." },
    zh = { ready="就绪", refresh="刷新", server="服务器状态", broadcast="广播整合包状态", close="关闭", active="已启用", missing="缺失", expected="预期", loaded="已加载", mods="个内含模组已启用", localScan="本地检查完成", requesting="正在查询服务器…", sending="正在发送管理员广播…", denied="需要管理员权限", admin="管理员工具", restart="模组变更需要协调重启，不会热重载文件。" }
}
local PZASM_WINDOW = nil
local PZASM_HUD_BUTTON = nil

local function pzasmLanguage()
    local value = "en"
    local ok, detected = pcall(function()
        if Translator and Translator.getLanguage then return tostring(Translator.getLanguage():name()) end
        if getCore and getCore().getOptionLanguageName then return tostring(getCore():getOptionLanguageName()) end
        return "en"
    end)
    if ok and detected then value = string.lower(detected) end
    if string.find(value, "fr") or string.find(value, "french") then return "fr" end
    if string.find(value, "es") or string.find(value, "spanish") then return "es" end
    if string.find(value, "de") or string.find(value, "german") then return "de" end
    if string.find(value, "pt") or string.find(value, "portugu") then return "pt" end
    if string.find(value, "zh") or string.find(value, "cn") or string.find(value, "chinese") then return "zh" end
    return "en"
end

local function pzasmText() return PZASM_TEXT[pzasmLanguage()] or PZASM_TEXT.en end

local function pzasmEscape(value)
    value = tostring(value or "")
    return string.gsub(string.gsub(value, "<", "&lt;"), ">", "&gt;")
end

local function pzasmIsAdmin()
    local ok, value = pcall(function() return string.lower(tostring(getAccessLevel() or "")) end)
    return ok and (value == "admin" or value == "moderator" or value == "overseer" or value == "gm")
end

local function pzasmRuntimeVersion(modId)
    local result = "—"
    pcall(function()
        local info = getModInfoByID(modId)
        if info and info.getVersion then result = tostring(info:getVersion()) end
    end)
    return result
end

PZASMControlWindow = ISPanel:derive("PZASMControlWindow")

function PZASMControlWindow:new(x, y, width, height)
    local panel = ISPanel.new(self, x, y, width, height)
    panel.backgroundColor = { r=0.035, g=0.052, b=0.040, a=0.98 }
    panel.borderColor = { r=0.48, g=0.72, b=0.25, a=1 }
    panel.moveWithMouse = true
    panel.serverStatus = "Ready"
    return panel
end

function PZASMControlWindow:initialise()
    ISPanel.initialise(self)
    local text = pzasmText()
    self.rich = ISRichTextPanel:new(22, 58, self.width - 44, self.height - 132)
    self.rich:initialise()
    self.rich:addScrollBars()
    self.rich.background = false
    self.rich.clip = true
    self:addChild(self.rich)

    self.status = ISLabel:new(22, self.height - 59, 20, text.ready, 0.70, 0.82, 0.68, 1, UIFont.Small, true)
    self.status:initialise()
    self:addChild(self.status)

    self.refreshButton = ISButton:new(self.width - 366, self.height - 68, 105, 34, text.refresh, self, PZASMControlWindow.onRefresh)
    self.refreshButton:initialise()
    self:addChild(self.refreshButton)

    self.serverButton = ISButton:new(self.width - 253, self.height - 68, 105, 34, text.server, self, PZASMControlWindow.onServerStatus)
    self.serverButton:initialise()
    self:addChild(self.serverButton)

    self.adminButton = ISButton:new(self.width - 366, self.height - 106, 218, 30, text.broadcast, self, PZASMControlWindow.onBroadcast)
    self.adminButton:initialise()
    self.adminButton:setVisible(pzasmIsAdmin())
    self:addChild(self.adminButton)

    self.closeButton = ISButton:new(self.width - 140, self.height - 68, 118, 34, text.close, self, PZASMControlWindow.onClose)
    self.closeButton:initialise()
    self:addChild(self.closeButton)
    self:refresh()
end

function PZASMControlWindow:prerender()
    ISPanel.prerender(self)
    self:drawRect(0, 0, self.width, 46, 0.98, 0.08, 0.14, 0.09)
    self:drawRect(0, 45, self.width, 2, 1, 0.48, 0.72, 0.25)
    self:drawText("PZ", 19, 13, 0.66, 0.86, 0.38, 1, UIFont.Medium)
    self:drawText("ADVANCED SERVER MANAGER", 58, 14, 0.92, 0.95, 0.90, 1, UIFont.Small)
    local role = pzasmIsAdmin() and "ADMIN" or "PLAYER"
    self:drawTextRight(role, self.width - 20, 15, 0.66, 0.86, 0.38, 1, UIFont.Small)
end

function PZASMControlWindow:refresh()
    local text = pzasmText()
    local active = getActivatedMods()
    local activeCount = 0
    local lines = {}
    for index, mod in ipairs(PZASM_MODS) do
        local enabled = active and active:contains(mod.id)
        if enabled then activeCount = activeCount + 1 end
        local color = enabled and "<RGB:0.55,0.86,0.36>" .. text.active or "<RGB:0.95,0.39,0.31>" .. text.missing
        lines[#lines + 1] = color .. "<RGB:1,1,1>  <B>" .. pzasmEscape(mod.name) .. "</B><LINE>" ..
            "<RGB:0.65,0.72,0.65>" .. text.expected .. " " .. pzasmEscape(mod.version) .. " · " .. text.loaded .. " " .. pzasmEscape(pzasmRuntimeVersion(mod.id)) ..
            " · Mod ID " .. pzasmEscape(mod.id) .. " · Workshop " .. pzasmEscape(mod.workshop) .. "<RGB:1,1,1><LINE>"
    end
    local adminText = pzasmIsAdmin() and "<LINE><RGB:0.85,0.68,0.25><B>" .. text.admin .. "</B><LINE>" .. text.restart .. "<RGB:1,1,1>" or ""
    self.rich.text = "<H1>" .. pzasmEscape(PZASM_PACK_NAME) .. "</H1><LINE>" ..
        "<RGB:0.65,0.72,0.65>Workshop " .. pzasmEscape(PZASM_WORKSHOP_ID) .. " · " .. tostring(activeCount) .. "/" .. tostring(#PZASM_MODS) .. " " .. text.mods .. " · F8<RGB:1,1,1><LINE><LINE>" ..
        table.concat(lines, "<LINE>") .. adminText
    self.rich:paginate()
    self.status:setName(tostring(activeCount) .. "/" .. tostring(#PZASM_MODS) .. " · " .. text.localScan)
end

function PZASMControlWindow:onRefresh() self:refresh() end
function PZASMControlWindow:onServerStatus()
    self.status:setName(pzasmText().requesting)
    pcall(function() sendClientCommand(getPlayer(), "PZASM_Control", "status", {}) end)
end
function PZASMControlWindow:onBroadcast()
    if not pzasmIsAdmin() then return end
    self.status:setName(pzasmText().sending)
    pcall(function() sendClientCommand(getPlayer(), "PZASM_Control", "broadcast", { pack = PZASM_PACK_NAME, workshop = PZASM_WORKSHOP_ID, count = #PZASM_MODS }) end)
end
function PZASMControlWindow:onClose() self:setVisible(false) end

local function pzasmOpenControl()
    if not PZASM_WINDOW then
        local width = math.min(900, getCore():getScreenWidth() - 70)
        local height = math.min(680, getCore():getScreenHeight() - 80)
        PZASM_WINDOW = PZASMControlWindow:new((getCore():getScreenWidth() - width) / 2, (getCore():getScreenHeight() - height) / 2, width, height)
        PZASM_WINDOW:initialise()
        PZASM_WINDOW:addToUIManager()
    else
        PZASM_WINDOW:setVisible(true)
        PZASM_WINDOW:bringToTop()
        PZASM_WINDOW:refresh()
    end
end

_G.PZASM_OpenControl = pzasmOpenControl

local function pzasmCreateHudButton()
    if PZASM_HUD_BUTTON then return end
    PZASM_HUD_BUTTON = ISButton:new(getCore():getScreenWidth() - 74, 54, 54, 34, "PZ", nil, pzasmOpenControl)
    PZASM_HUD_BUTTON:initialise()
    PZASM_HUD_BUTTON:setAnchorLeft(false)
    PZASM_HUD_BUTTON:setAnchorRight(true)
    PZASM_HUD_BUTTON:addToUIManager()
end

local function pzasmKeyPressed(key)
    if Keyboard and key == Keyboard.KEY_F8 then pzasmOpenControl() end
end

local function pzasmServerCommand(module, command, args)
    if module ~= "PZASM_Control" then return end
    if command == "status" and PZASM_WINDOW then
        PZASM_WINDOW.status:setName("Server online · " .. tostring(args.players or 0) .. " player(s) · " .. tostring(args.expected or #PZASM_MODS) .. " expected mods")
    elseif command == "announcement" then
        if HaloTextHelper and getPlayer() then HaloTextHelper.addText(getPlayer(), tostring(args.message or "Pack status updated"), HaloTextHelper.getColorGreen()) end
    elseif command == "denied" and PZASM_WINDOW then
        PZASM_WINDOW.status:setName(pzasmText().denied)
    end
end

Events.OnGameStart.Add(pzasmCreateHudButton)
Events.OnKeyPressed.Add(pzasmKeyPressed)
Events.OnServerCommand.Add(pzasmServerCommand)
""";
    }

    private static string CreateServer(PackageProject project) => $$"""
local PZASM_EXPECTED_MODS = {{project.Mods.Count(x => x.Enabled)}}

local function pzasmIsAdmin(player)
    if not player then return false end
    local value = string.lower(tostring(player:getAccessLevel() or ""))
    return value == "admin" or value == "moderator" or value == "overseer" or value == "gm"
end

local function pzasmPlayerCount()
    local ok, players = pcall(function() return getOnlinePlayers() end)
    return ok and players and players:size() or 0
end

local function pzasmClientCommand(module, command, player, args)
    if module ~= "PZASM_Control" then return end
    if command == "status" then
        sendServerCommand(player, "PZASM_Control", "status", { players = pzasmPlayerCount(), expected = PZASM_EXPECTED_MODS })
        return
    end
    if command == "broadcast" then
        if not pzasmIsAdmin(player) then
            sendServerCommand(player, "PZASM_Control", "denied", {})
            return
        end
        local pack = tostring(args and args.pack or "server pack")
        local message = "[PZASM] " .. pack .. ": " .. tostring(PZASM_EXPECTED_MODS) .. " managed mods active. Changes require a coordinated restart."
        sendServerCommand("PZASM_Control", "announcement", { message = message })
    end
end

Events.OnClientCommand.Add(pzasmClientCommand)
""";

    private static string LuaString(string value) => "\"" + value
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal)
        .Replace("\r", string.Empty, StringComparison.Ordinal)
        .Replace("\n", "\\n", StringComparison.Ordinal) + "\"";
}
